name: CI Pipeline (PRs and pushes main)
run-name: Merged to main by ${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package with pip
        run: |
          pipx install hatch
          hatch env create dev

      - name: Run tests
        run: |
          hatch run dev:pytest

      - name: Run fermo_core on test dataset
        run: |
          hatch run dev:fermo_core --parameters tests/test_data/test.parameters.json