name: CI Pipeline (PRs and pushes main)
run-name: Merged to main by ${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run unit tests
        run: |
          pytest --run_slow

      - name: Run fermo_core wo params
        id: run_program
        run: |
          python fermo_core/main.py || echo $? > error_code.txt
      
      - name: Check for specific error code
        if: steps.run_program.outcome == 'failure'
        run: |
          error_code=$(cat error_code.txt)
          if [ "$error_code" -eq 2 ]; then
            echo "fermo_core started successfully."
            exit 0
          else
            echo "Program failed with a different error code: $error_code"
            exit 1
          fi
